apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  # POSTGRES_DB: stonebank
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_MULTIPLE_DATABASES: "lab,lab,lab:stonebank,stonebank,stonebank:chat,chat,chat"